# Site settings
title: MattWeinberg.net
description: "Matt Weinberg's website."
url: "https://mattweinberg.net"
baseurl: ""
permalink: /:title:output_ext


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  style: compressed


